Repository obed-kmitl/obed-frontend, pull requests merged in 2022-01, with the labels that each got.

#24 Feature/#111 teacher activity overview tab
  src/App.jsx
  src/components/ActivityList/ActivityList.jsx
  src/components/ActivityList/ActivityList.module.scss
  src/components/ActivityOverview/ActivityOverview.jsx
  src/components/ActivityOverview/ActivityOverview.module.scss
  src/components/ActivityOverview/hooks/useActivityOverview.js
  src/components/ActivityTable/ActivityTable.jsx
  src/components/ActivityTable/ActivityTable.module.scss
  src/components/ActivityTable/hooks/useActivityTable.js
  src/components/index.js
  src/pages/ActivityDetail/ActivityDetail.jsx
  src/pages/ActivityDetail/ActivityDetail.module.scss
  src/pages/ActivityDetail/hooks/useActivityDetail.js
  src/pages/index.js
Labels: enhancement

#25 Feature/#111 teacher activity overview tab
  src/components/ActivityCard/ActivityCard.jsx
  src/components/ActivityList/ActivityList.jsx
  src/components/ActivityList/ActivityList.module.scss
  src/components/ActivityList/hooks/useActivity.js
  src/pages/Activity/Activity.jsx
  src/pages/ActivityDetail/ActivityDetail.jsx
Labels: enhancement

#26 Feature/#110 report page
  package.json
  src/App.jsx
  src/components/CourseCard/CourseCard.module.scss
  src/components/Layout/Navbar/Navbar.jsx
  src/components/TeacherReportForm/TeacherReportForm.jsx
  src/components/TeacherReportForm/TeacherReportForm.module.scss
  src/components/index.js
  src/index.js
  src/pages/TeacherReport/TeacherReport.jsx
  src/pages/TeacherReport/TeacherReport.module.scss
  src/pages/index.js
  yarn.lock
Labels: enhancement

#27 Feature/#112 teacher activity group tab
  src/components/ActivityGroup/ActivityGroup.jsx
  src/components/ActivityGroup/ActivityGroup.module.scss
  src/components/ActivityOverview/ActivityOverview.jsx
  src/components/ActivityOverview/ActivityOverview.module.scss
  src/components/ActivityOverview/hooks/useActivityOverview.js
  src/components/Layout/Navbar/Navbar.jsx
  src/components/index.js
  src/pages/Activity/Activity.jsx
  src/pages/ActivityDetail/ActivityDetail.jsx
  src/pages/ActivityDetail/hooks/useActivityDetail.js
Labels: bug

#28 Feature/#114 teacher rubric tab
  src/components/ActivityRubric/ActivityRubric.jsx
  src/components/ActivityRubric/ActivityRubric.module.scss
  src/components/CourseTable/CourseTable.jsx
  src/components/CourseTable/hooks/useCourse.js
  src/components/Layout/Navbar/Navbar.jsx
  src/components/Standard/Standard.jsx
  src/components/index.js
  src/pages/ActivityDetail/ActivityDetail.jsx
  src/pages/Curriculum/Curriculum.jsx
  src/pages/Curriculum/hooks/useCurriculum.js
  src/pages/Home/Home.jsx
  src/pages/Teacher/Teacher.jsx
  src/pages/Teacher/hooks/useTeacher.js
Labels: enhancement

#29 Feature/#125 admin report page
  src/App.jsx
  src/components/Layout/Navbar/Navbar.jsx
  src/pages/AdminGraph/AdminGraph.jsx
  src/pages/AdminGraph/AdminGraph.module.scss
  src/pages/AdminReport/AdminReport.jsx
  src/pages/AdminReport/AdminReport.module.scss
  src/pages/NotFound/NotFound.jsx
  src/pages/index.js
Labels: enhancement

#30 Feature#113/activity grading tab
  src/components/ActivityGrading/ActivityGrading.jsx
  src/components/ActivityGrading/ActivityGrading.module.scss
  src/components/ActivityGrading/hooks/useActivityGrading.js
  src/components/ActivityGradingGroup/ActivityGradingGroup.jsx
  src/components/ActivityGradingGroup/ActivityGradingGroup.module.scss
  src/components/ActivityGradingGroup/hooks/useActivityGradingGroup.js
  src/components/ActivityGroup/ActivityGroup.jsx
  src/components/ActivityGroup/ActivityGroup.module.scss
  src/components/ActivityList/ActivityList.jsx
  src/components/index.js
  src/pages/ActivityDetail/ActivityDetail.jsx
  src/pages/ActivityDetail/hooks/useActivityDetail.js
  src/pages/Home/Home.jsx
Labels: enhancement

#31 handle error notification
  src/components/Standard/hooks/useStandard.js
  src/components/Standard/hooks/useSubStandard.js
  src/utils/notification.js
Labels: enhancement

#32 add option to create or duplicate semester
  src/pages/Plan/Plan.jsx
  src/pages/Plan/hooks/useSemester.js
Labels: enhancement

#33 Feature/#133 integrate activity page
  src/components/ActivityCard/ActivityCard.jsx
  src/components/ActivityCard/ActivityCard.module.scss
  src/components/ActivityList/ActivityList.jsx
  src/components/ActivityList/hooks/useActivity.js
  src/components/SectionTable/SectionTable.jsx
  src/components/WeightingTable/WeightingTable.jsx
  src/components/WeightingTable/WeightingTable.module.scss
  src/components/WeightingTable/hooks/useWeighting.js
  src/components/index.js
  src/pages/Plan/Plan.jsx
  src/pages/Plan/hooks/useSemester.js
  src/pages/Planning/Planning.jsx
  src/pages/Planning/Planning.module.scss
  src/pages/Planning/hooks/useWeighting.js
Labels: bug, enhancement

#34 fix UX save mapping
  src/components/MappingStandard/MappingStandard.jsx
  src/components/MappingStandard/MappingTable.jsx
Labels: enhancement
